/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about the current state of the pagination.
 */
export interface AltoBaseResponsePaginatedDtoMetaApi { 
    /**
     * The number of items sent per page.
     */
    itemsPerPage: number;
    /**
     * The total number of items retrieved by the database query.
     */
    totalItems: number;
    /**
     * The current page of the paginated response.
     */
    currentPage: number;
    /**
     * The total number of pages in the paginated response. This property is calculated from itemPerPage and totalItems.
     */
    totalPage: number;
    /**
     * The current url
     */
    currentUrl: string;
    /**
     * The pagination previous url
     */
    previousUrl?: string;
    /**
     * The pagination next url
     */
    nextUrl?: string;
}

