/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeStateEnumApi } from './challengeStateEnum';
import { ChallengeAssignmentApi } from './challengeAssignment';
import { TeamApi } from './team';
import { ChallengeTypeEnumApi } from './challengeTypeEnum';


export interface ChallengeApi { 
    id: string;
    createdBy: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date;
    type: ChallengeTypeEnumApi;
    status: ChallengeStateEnumApi;
    name: string;
    guessesPerDay: number;
    reward: string;
    scoreMinPercent: number;
    startDate: Date;
    endDate: Date;
    leadUser: string;
    leadTeam: TeamApi;
    teams: Array<TeamApi>;
    assignments: Array<ChallengeAssignmentApi>;
    /**
     * The bubble ID  ! This field is temporary and will be deleted once all the migration are finished
     */
    tempBubbleId?: string;
}



