/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyLightDtoApi } from './companyLightDto';
import { UserLightDtoApi } from './userLightDto';
import { QuestionLightDtoApi } from './questionLightDto';


export interface CommentDtoApi { 
    question: QuestionLightDtoApi;
    questionId: string;
    text: string;
    image?: string;
    isRead: boolean;
    company: CompanyLightDtoApi;
    companyId: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}

