/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserLightDtoApi } from './userLightDto';


export interface CompanyDtoApi { 
    domain?: string;
    name: string;
    isSlackActive?: boolean;
    slackDays?: Array<CompanyDtoApiSlackDaysEnumApi>;
    slackQuestionsPerQuiz?: number;
    slackTimes?: Array<CompanyDtoApiSlackTimesEnumApi>;
    slackAdmin?: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}
export enum CompanyDtoApiSlackDaysEnumApi {
    Monday = 'Monday',
    Tuesday = 'Tuesday',
    Wednesday = 'Wednesday',
    Thursday = 'Thursday',
    Friday = 'Friday'
};
export enum CompanyDtoApiSlackTimesEnumApi {
    _10h = '10h',
    _13h30 = '13h30',
    _17h = '17h'
};



