/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTeamDtoApi { 
    createdBy?: string;
    companyId?: string;
    /**
     * The long name of the team.
     */
    longName: string;
    /**
     * The short name of the team.
     */
    shortName: string;
}

