/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuessSourceEnumApi } from './guessSourceEnum';
import { ProgramRunApi } from './programRun';
import { ProgramRunQuestionApi } from './programRunQuestion';
import { QuestionApi } from './question';


export interface GuessApi { 
    id: string;
    createdBy: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date;
    source: GuessSourceEnumApi;
    question: QuestionApi;
    questionId?: string;
    programRun?: ProgramRunApi;
    programRunQuestion: ProgramRunQuestionApi;
    programRunId?: string;
    answers: Array<string>;
    isValid: boolean;
    isTimedOut: boolean;
    /**
     * The team ID of the guess creator (if any)
     */
    teamId?: string;
    isUnknownSelected: boolean;
    /**
     * The bubble ID  ! This field is temporary and will be deleted once all the migration are finished
     */
    tempBubbleId?: string;
}



