/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyLightDtoApi } from './companyLightDto';
import { UserLightDtoApi } from './userLightDto';
import { TeamLightDtoApi } from './teamLightDto';
import { ProgramRunLightDtoApi } from './programRunLightDto';
import { QuestionLightDtoApi } from './questionLightDto';


export interface GuessDtoApi { 
    questionId?: string;
    question?: QuestionLightDtoApi;
    programRun?: ProgramRunLightDtoApi;
    programRunId?: string;
    answers?: Array<string>;
    isValid: boolean;
    isTimedOut: boolean;
    team?: TeamLightDtoApi;
    teamId?: string;
    source: GuessDtoApiSourceEnumApi;
    company: CompanyLightDtoApi;
    companyId: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}
export enum GuessDtoApiSourceEnumApi {
    Web = 'web',
    Slack = 'slack',
    Teams = 'teams',
    Unknown = 'unknown'
};



