/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NextQuestionsDtoApi { 
    /**
     * An array of  IDs used to filter the results to only include entities with the specified IDs
     */
    ids?: string;
    /**
     * The ID of the user sending the request.  This field is required when using the API Key.  It will be included in the JSON Web Token (JWT) when using Auth0 authentication.
     */
    userId?: string;
    /**
     * The page of results to retrieve.
     */
    page?: number;
    /**
     * The number of items per page to retrieve.
     */
    itemsPerPage?: number;
    /**
     * The ID of the company that the user sending the request is related to.  This field is required when using the API Key.  It will be included in the JSON Web Token (JWT) when using Auth0 authentication.
     */
    companyId?: string;
}

