/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriorityEnumApi } from './priorityEnum';
import { TeamApi } from './team';
import { TagApi } from './tag';


export interface PatchProgramDtoApi { 
    priority?: PriorityEnumApi;
    /**
     * Specifies whether the program is active or not. Optional.
     */
    isActive?: boolean;
    /**
     * Specifies the name of the program. Required.
     */
    name?: string;
    /**
     * Specifies the description of the program. Optional.
     */
    description?: string;
    /**
     * Specifies the expected score. Optional.
     */
    expectation?: number;
    /**
     * Specifies whether the program should display a timer or not. Optional.
     */
    showTimer?: boolean;
    /**
     * Specifies the tags associated with the program. Optional.
     */
    tags?: Array<TagApi>;
    /**
     * Specifies the teams associated with the program. Optional.
     */
    teams?: Array<TeamApi>;
}



