/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriorityEnumApi } from './priorityEnum';
import { TeamApi } from './team';
import { ProgramRunApi } from './programRun';
import { ProgramAssignmentApi } from './programAssignment';
import { QuestionApi } from './question';
import { TagApi } from './tag';


export interface ProgramApi { 
    id: string;
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    priority: PriorityEnumApi;
    isActive: boolean;
    name: string;
    description?: string;
    expectation: number;
    showTimer: boolean;
    tags?: Array<TagApi>;
    questions?: Array<QuestionApi>;
    teams: Array<TeamApi>;
    assignments: Array<ProgramAssignmentApi>;
    runs: Array<ProgramRunApi>;
    /**
     * The bubble ID  ! This field is temporary and will be deleted once all the migration are finished
     */
    tempBubbleId?: string;
}



