/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgramRunApi } from './programRun';
import { QuestionApi } from './question';
import { GuessApi } from './guess';


export interface ProgramRunQuestionApi { 
    id: string;
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    programRun: ProgramRunApi;
    programRunId: string;
    question: QuestionApi;
    questionId: string;
    guess: GuessApi;
    /**
     * The bubble ID  ! This field is temporary and will be deleted once all the migration are finished
     */
    tempBubbleId?: string;
}

