/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyLightDtoApi } from './companyLightDto';
import { UserLightDtoApi } from './userLightDto';
import { TeamLightDtoApi } from './teamLightDto';
import { TagLightDtoApi } from './tagLightDto';


export interface ProgramDtoApi { 
    isActive: boolean;
    name: string;
    description?: string;
    expectation: number;
    priority: ProgramDtoApiPriorityEnumApi;
    showTimer: boolean;
    tags?: Array<TagLightDtoApi>;
    teams: Array<TeamLightDtoApi>;
    company: CompanyLightDtoApi;
    companyId: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}
export enum ProgramDtoApiPriorityEnumApi {
    High = 'High',
    Low = 'Low',
    Medium = 'Medium'
};



