/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionSubmittedStatusEnumApi } from './questionSubmittedStatusEnum';


export interface QuestionSubmittedApi { 
    id: string;
    createdBy: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date;
    status: QuestionSubmittedStatusEnumApi;
    /**
     * The title of the question-submitted. It\'s the actual question written by the user.
     */
    title: string;
}



