/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentLightDtoApi } from './commentLightDto';
import { CompanyLightDtoApi } from './companyLightDto';
import { UserLightDtoApi } from './userLightDto';
import { ProgramLightDtoApi } from './programLightDto';
import { TagLightDtoApi } from './tagLightDto';


export interface QuestionDtoApi { 
    title: string;
    type: QuestionDtoApiTypeEnumApi;
    tags?: Array<TagLightDtoApi>;
    programs?: Array<ProgramLightDtoApi>;
    answerType: QuestionDtoApiAnswerTypeEnumApi;
    answersAccepted: Array<string>;
    answersWrong: Array<string>;
    explanation?: string;
    link?: string;
    comments?: Array<CommentLightDtoApi>;
    relevance?: number;
    company: CompanyLightDtoApi;
    companyId: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}
export enum QuestionDtoApiTypeEnumApi {
    MultipleChoice = 'multiple_choice',
    FreeText = 'free_text',
    NumberRange = 'number_range'
};
export enum QuestionDtoApiAnswerTypeEnumApi {
    Text = 'text',
    Number = 'number',
    Date = 'date'
};



