/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreTypeEnumApi } from './scoreTypeEnum';
import { ScoreTimeframeEnumApi } from './scoreTimeframeEnum';
import { ScoreByTypeEnumApi } from './scoreByTypeEnum';
import { ScoreDtoApi } from './scoreDto';


export interface ScoresResponseDtoApi { 
    type: ScoreTypeEnumApi;
    timeframe: ScoreTimeframeEnumApi;
    scoredBy?: ScoreByTypeEnumApi;
    /**
     * Company ID. Must be a UUID string.
     */
    companyId: string;
    /**
     * An array of score objects.
     */
    scores: Array<ScoreDtoApi>;
    /**
     * The ID for the type to filter by
     */
    scoredById?: string;
    /**
     * The minimum number of total counts.
     */
    countGreaterThan?: number;
    /**
     * The earliest date to include in the score.
     */
    dateAfter?: Date;
    /**
     * The latest date to include in the score.
     */
    dateBefore?: Date;
}



