/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScoreDtoApi { 
    /**
     * An array of average scores, where each element corresponds to a timeframe. For example, if the timeframe is \"week\", each element in this array will represent the average score for a week.
     */
    averages: Array<number>;
    /**
     * An array of total scores, where each element corresponds to a timeframe. For example, if the timeframe is \"week\", each element in this array will represent the total guesses for a week.
     */
    counts: Array<number>;
    /**
     * An array of valid scores, where each element corresponds to a timeframe. For example, if the timeframe is \"week\", each element in this array will represent the number of valid guesses for a week.
     */
    valids: Array<number>;
    /**
     * An array of dates, where each element corresponds to a timeframe. For example, if the timeframe is \"week\", each element in this array will represent the start date of the week.
     */
    dates: Array<Date>;
    /**
     * The label for the score, which can be a tag name for example on scores with a Type Tag.
     */
    label: string;
    /**
     * The unique identifier for the score type element.  The tag.id for example on scores with a type Tag.
     */
    id: string;
}

