/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StreakDtoApi { 
    /**
     * The start date of the streak
     */
    startDate: Date;
    /**
     * The count of days in the streak
     */
    count: number;
}

