/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgramApi } from './program';
import { QuestionApi } from './question';


export interface TagApi { 
    id: string;
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    description?: string;
    /**
     * The bubble ID  ! This field is temporary and will be deleted once all the migration are finished
     */
    tempBubbleId?: string;
    questions: Array<QuestionApi>;
    programs: Array<ProgramApi>;
}

