/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagDtoApi } from './tagDto';


export interface TagDtoResponseAllOfApi { 
    statusCode?: number;
    data?: TagDtoApi;
}

