/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsDtoApi } from './statsDto';


export interface TeamStatsDtoApi { 
    programs?: Array<StatsDtoApi>;
    tags?: Array<StatsDtoApi>;
    id: string;
    label: string;
    totalGuessesCount: number;
    validGuessesCount: number;
    score?: number;
}

