/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyLightDtoApi } from './companyLightDto';
import { StreakDtoApi } from './streakDto';
import { UserLightDtoApi } from './userLightDto';
import { TeamLightDtoApi } from './teamLightDto';


export interface UserDtoApi { 
    auth0Id: string;
    email: string;
    team?: TeamLightDtoApi;
    teamId?: string;
    roles: Array<UserDtoApiRolesEnumApi>;
    pref?: object;
    bubbleId?: string;
    username?: string;
    pictureUrl?: string;
    firstname?: string;
    lastname?: string;
    timezone?: string;
    country?: string;
    slackId?: string;
    slackBotChannel?: string;
    isActive: boolean;
    longestStreak: StreakDtoApi;
    currentStreak: StreakDtoApi;
    company: CompanyLightDtoApi;
    companyId: string;
    id: string;
    createdAt: Date;
    createdBy: string;
    createdByUser: UserLightDtoApi;
    updatedAt: Date;
    deletedAt?: Date;
}
export enum UserDtoApiRolesEnumApi {
    AltoAdmin = 'alto-admin',
    CompanyAdmin = 'company-admin',
    CompanyUser = 'company-user'
};



