/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AltoBaseResponsePaginatedDtoMetaApi } from './altoBaseResponsePaginatedDtoMeta';
import { UserDtoApi } from './userDto';


export interface UserDtoPaginatedResponseApi { 
    statusCode: number;
    data?: Array<UserDtoApi>;
    meta: AltoBaseResponsePaginatedDtoMetaApi;
}

