/**
 * Usealto API [DEV]
 * The usealto (also called alto) API swagger documentation
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEnumApi } from './roleEnum';


export interface UserApi { 
    id: string;
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    roles: Array<RoleEnumApi>;
    auth0Id: string;
    email: string;
    teamId?: string;
    pref?: object;
    bubbleId?: string;
    username?: string;
    pictureUrl?: string;
    firstname?: string;
    lastname?: string;
    timezone?: string;
    country?: string;
    slackId?: string;
    slackBotChannel?: string;
}

